language: node_js
node_js: '6'
services: mongodb
addons:
  hosts:
    - mongodb
install:
  - yarn
cache: yarn
before_script:
  - cp ${TRAVIS_BUILD_DIR}/config/default.template.json ${TRAVIS_BUILD_DIR}/config/default.json
